"""Add WeatherObservation model and Claim source_metadata

Revision ID: d463e8c4538b
Revises: f63a54b52a59
Create Date: 2026-04-15 00:38:50.117468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd463e8c4538b'
down_revision: Union[str, Sequence[str], None] = 'f63a54b52a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('temp_celsius', sa.Float(), nullable=True),
    sa.Column('rainfall_mm_hr', sa.Float(), nullable=True),
    sa.Column('aqi', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('api_provider', sa.String(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_observations_id'), 'weather_observations', ['id'], unique=False)
    op.create_index(op.f('ix_weather_observations_observed_at'), 'weather_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_weather_observations_zone_id'), 'weather_observations', ['zone_id'], unique=False)
    op.add_column('claims', sa.Column('source_metadata', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'source_metadata')
    op.drop_index(op.f('ix_weather_observations_zone_id'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_observed_at'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_id'), table_name='weather_observations')
    op.drop_table('weather_observations')
    # ### end Alembic commands ###
