"""Initial schema

Revision ID: f63a54b52a59
Revises: 
Create Date: 2026-04-15 00:22:11.019144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f63a54b52a59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM type if it doesn't exist
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)

    # Check if the enum type already exists
    existing_enums = conn.execute(sa.text(
        "SELECT typname FROM pg_type WHERE typname = 'triggertype'"
    )).fetchone()

    if not existing_enums:
        conn.execute(sa.text(
            "CREATE TYPE triggertype AS ENUM ('RAIN', 'HEAT', 'AQI', 'SHUTDOWN', 'CLOSURE')"
        ))

    op.create_table('sustained_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.Enum('RAIN', 'HEAT', 'AQI', 'SHUTDOWN', 'CLOSURE', name='triggertype', create_type=False), nullable=False),
    sa.Column('consecutive_days', sa.Integer(), nullable=True),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_sustained', sa.Boolean(), nullable=True),
    sa.Column('history_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sustained_events_id'), 'sustained_events', ['id'], unique=False)
    op.create_index(op.f('ix_sustained_events_zone_id'), 'sustained_events', ['zone_id'], unique=False)
    op.create_table('partner_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_devices_device_id'), 'partner_devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_partner_devices_id'), 'partner_devices', ['id'], unique=False)
    op.create_index(op.f('ix_partner_devices_partner_id'), 'partner_devices', ['partner_id'], unique=False)
    op.create_table('partner_gps_pings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_gps_pings_created_at'), 'partner_gps_pings', ['created_at'], unique=False)
    op.create_index(op.f('ix_partner_gps_pings_id'), 'partner_gps_pings', ['id'], unique=False)
    op.create_index(op.f('ix_partner_gps_pings_partner_id'), 'partner_gps_pings', ['partner_id'], unique=False)
    op.drop_table('partner_runtime_metadata')
    op.drop_table('partner_platform_activity')
    op.drop_table('zone_coverage_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone_coverage_metadata',
    sa.Column('zone_id', sa.INTEGER(), nullable=True),
    sa.Column('pin_codes_json', sa.TEXT(), nullable=True),
    sa.Column('density_weight', sa.REAL(), nullable=True),
    sa.Column('ward_name', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('zone_id')
    )
    op.create_table('partner_platform_activity',
    sa.Column('partner_id', sa.INTEGER(), nullable=True),
    sa.Column('platform_logged_in', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.Column('active_shift', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.Column('orders_accepted_recent', sa.INTEGER(), server_default=sa.text('5'), nullable=False),
    sa.Column('orders_completed_recent', sa.INTEGER(), server_default=sa.text('4'), nullable=False),
    sa.Column('last_app_ping', sa.TEXT(), nullable=False),
    sa.Column('zone_dwell_minutes', sa.INTEGER(), server_default=sa.text('(60)'), nullable=False),
    sa.Column('suspicious_inactivity', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('platform', sa.TEXT(), server_default=sa.text("'zomato'"), nullable=False),
    sa.Column('updated_at', sa.TEXT(), nullable=False),
    sa.Column('source', sa.TEXT(), server_default=sa.text("'simulated'"), nullable=False),
    sa.PrimaryKeyConstraint('partner_id')
    )
    op.create_table('partner_runtime_metadata',
    sa.Column('partner_id', sa.INTEGER(), nullable=True),
    sa.Column('pin_code', sa.TEXT(), nullable=True),
    sa.Column('is_manual_offline', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('manual_offline_until', sa.TEXT(), nullable=True),
    sa.Column('leave_until', sa.TEXT(), nullable=True),
    sa.Column('leave_note', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('partner_id')
    )
    op.drop_index(op.f('ix_partner_gps_pings_partner_id'), table_name='partner_gps_pings')
    op.drop_index(op.f('ix_partner_gps_pings_id'), table_name='partner_gps_pings')
    op.drop_index(op.f('ix_partner_gps_pings_created_at'), table_name='partner_gps_pings')
    op.drop_table('partner_gps_pings')
    op.drop_index(op.f('ix_partner_devices_partner_id'), table_name='partner_devices')
    op.drop_index(op.f('ix_partner_devices_id'), table_name='partner_devices')
    op.drop_index(op.f('ix_partner_devices_device_id'), table_name='partner_devices')
    op.drop_table('partner_devices')
    op.drop_index(op.f('ix_sustained_events_zone_id'), table_name='sustained_events')
    op.drop_index(op.f('ix_sustained_events_id'), table_name='sustained_events')
    op.drop_table('sustained_events')
    # ### end Alembic commands ###
